development:
  adapter: postgresql
  encoding: unicode
  database: quantified_dance_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quantified_dance_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: quantified_dance
  pool: 5
  username: postgres
  password:
